export const listUsers = [
  { name: "Dani e Gerson", number: 1 },
  { name: "Juraci Rank", number: 2 },
  { name: "Juraci Rank", number: 3 },
  { name: "Juraci Rank", number: 4 },
  { name: "Juraci Rank", number: 5 },
  { name: "Gilmar", number: 6 },
  { name: "Rosicler", number: 7 },
  { name: "Vanessa", number: 13 },
  { name: "Rubi", number: 14 },
  { name: "Gilmar", number: 15 },
  { name: "Vó Inez", number: 18 },
  { name: "Gilmar", number: 24 },
  { name: "Gilmar", number: 26 },
  { name: "Digão", number: 27 },
  { name: "Kelly", number: 35 },
  { name: "Jordan", number: 37 },
  { name: "Jeane", number: 40 },
  { name: "Ivonete", number: 47 },
  { name: "Família Kopaceck Fernandes", number: 59 },
  { name: "Scheila", number: 80 },
  { name: "Rose Teixeira", number: 81 },
  { name: "Tia Josi", number: 82 },
  { name: "Tia Josi", number: 83 },
  { name: "Bisa Jô", number: 84 },
  { name: "Tânia", number: 85 },
  { name: "Gilmar", number: 86 },
  { name: "Nika", number: 87 },
  { name: "Roseane", number: 88 },
  { name: "Juce", number: 89 },
  { name: "Anielli", number: 90 },
  { name: "Dani e Gerson", number: 91 },
  { name: "Gilmar", number: 92 },
  { name: "Gilmar", number: 93 },
  { name: "Tânia", number: 94 },
  { name: "Rose Teixeira", number: 95 },
  { name: "Gilmar", number: 96 },
  { name: "Leila", number: 97 },
  { name: "Rose Teixeira", number: 98 },
  { name: "Gilmar", number: 99 },
  { name: "Adriana e Lauro", number: 100 },
];
